server:
    static_dirs: [
        '/home/alexander/projects/homebusiness/homebusiness/homebusiness/static'
    ]
smtp:
    ssl: true,
    host: 'smtp.mail.ru'
    port: 465
    user: 'triplustri@mail.ru'
    password: '99@marmazetka'
    from: 'triplustri@mail.ru'
