server:
    static_dirs: [
        './static'
    ]
    locale: 'ru_RU'
gunicorn:
    bind: '127.0.0.1:8001'
smtp:
    ssl: true
    host: 'smtp.mail.ru'
    port: 465
    user: 'triplustri@mail.ru'
    password: '99@marmazetka'
    from: 'triplustri@mail.ru'
database:
    # sqlite, postgres, mysql
    driver: 'postgres'
    host: 'localhost'
    port: 5432
    user: 'alexander'
security:
    secret: 'eyJhbGciOiAiSFMyNTYiLCAidHlwIj'
i18n:
    load_paths: ['./resource/i18n']
